inherits:
  - strictness_high


ignore:
  - venv
  - test
  - .pytest_cache/


output-format: grouped


test-warnings: false
doc-warnings: false


autodetect: false


pep8:
    run: true
    options:
        max-line-length: 120


pylint:
    run: true
    options:
        max-line-length: 120
        ignored-classes: pytest

    disable:
        - C0302
        - W0142
        - W0141
        - E0401
        - C0411
        - C0412
        - W0718
        - E1120
        - E1123
        - R0916